name: fotocopy_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  geolocator: ^7.0.0
  geocoding: ^3.0.0
  path_provider: ^2.1.3
  pdf: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/clients.png
  - assets/employee.png
  - assets/inprogress.png
  - assets/inventory.png
  - assets/Laki-laki.png
  - assets/Perempuan.png
  - assets/no_stock.png
  - assets/product.png
  - assets/ready-stock.png
  - assets/remove.gif
  - assets/services.png
  - assets/no-data.gif
  - assets/absen.jpg
